Repository SwArch-2025-1-2A/groups_ms, pull requests merged in 2025-05, with the labels that each got.

#1 Initialize project
  .gitignore
  .vscode/extensions.json
  Dockerfile
  README.md
  go.mod
  go.sum
  main.go
Labels: documentation, enhancement

#3 UUID override
  main.go
  repository/events.sql.go
  repository/groups.sql.go
  repository/models.go
  repository/users.sql.go
  sqlc.yml
Labels: enhancement

#5 Improve documentation
  README.md
Labels: documentation

#4 Implement skeleton for GraphQL API
  .dockerignore
  .prodignore
  Dockerfile
  README.md
  docker-compose.yml
  go.mod
  go.sum
  gqlgen.yml
  graph/generated.go
  graph/model/models_gen.go
  graph/resolver.go
  graph/schema.graphqls
  graph/schema.resolvers.go
  main.go
  server.go
  start.sh
Labels: enhancement

#7 Create table of contents
  README.md
Labels: documentation

#10 Standardize docker services
  .dockerignore
  .env.example
  .prodignore
  README.md
  docker-compose.yml
Labels: documentation, enhancement, Docker

#13 Add `container_name`
  docker-compose.yml
Labels: bug, Docker
